[package]
name = "zero2prod"
version = "0.1.0"
authors = ["Michael Hrenka <radivis@radivis.com>"]
edition = "2024"

[dependencies]
actix-web = "4"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

# Dev dependencies are used exclusively when running tests or examples
# They do not get included in the final application binary!
[dev-dependencies]
reqwest = "0.12.24"